# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
version: 2
language: "es-ES"
reviews:
  profile: "chill"
  auto_review:
    enabled: true
    drafts: false
  tools:
    ast-grep:
      enabled: true
    shellcheck:
      enabled: true
chat:
  auto_reply: true
