export const styles = { 
  containerCard: "rounded-2xl bg-white dark:bg-black2 p-3 shadow-lg gap-2 w-full mt-2 text-gray-900 dark:text-white",
  sectionTitle: "text-lg font-bold mb-2 text-gray-900 dark:text-gray-100",
  input: "my-1 rounded-md border border-gray-300 dark:border-gray-600 p-2 bg-white dark:bg-black3 text-gray-900 dark:text-white",
  noteInput: "my-1 h-20 rounded-md border border-gray-300 dark:border-gray-600 p-2 bg-white dark:bg-black3 text-gray-900 dark:text-white",
  buttonRow: "flex-row gap-2 mt-2",
  houseItem: "border-b border-gray-300 dark:border-gray-600 p-2 flex-row justify-between items-center text-gray-900 dark:text-white",
  textInput: "my-1 rounded-md border border-gray-300 dark:border-gray-600 p-2 bg-white dark:bg-black3 text-gray-900 dark:text-white",
  loginPage: "bg-white dark:bg-black1 text-gray-900 dark:text-white",
  loginTitle: "text-4xl font-bold mb-1 text-gray-900 dark:text-white",
  loginDescription: "font-bold mb-1 text-gray-400 dark:text-gray-500",
  pageTitle: "mb-4 text-center text-2xl font-bold text-gray-900 dark:text-white",
  containerPage: "px-4 py-2 shadow bg-white dark:bg-black1 text-gray-900 dark:text-white",
  SAV: "flex-1 bg-gray-100 dark:bg-black1 text-gray-900 dark:text-white",
};
